### PR TITLE
Fix top bonds

### PR DESCRIPTION
**Pull request by mjtadema**
Included those lysozyme topology files for testing.
parse_tpr and parse_top should now generate identical graphs.

### CODE REVIEW

**Comment by mjtadema** [comment]
Fixed #16

**Comment by brisvag** [comment]
I get some error both with tpr and with top parsing, and no bonds are shown. I will check it tomorrow.

**Comment by brisvag** [comment]
This is now working properly! I think we should remove the progress printing until we have a better implementation, then merge the PR. We can add it back later in a separate PR!

**Comment by mjtadema** [comment]
Alright, removed the progress thingy.
but yes it is getting big.
We might have to put everything into a library for the parsing and have only cg_bonds in the script.

**Pull request merged**
