### PR TITLE
Finally a module!

### PR DESCRIPTION
**Pull request by brisvag**
I refactore the code into a few separate moduled.
- `pycg_bonds.py` now only contains `make_graphs` and `pycg_bonds`.
- `parse_top` and `parse_tpr` now have each their own file
- utility functions were all moved in `utils.py`

Also, I added some shit at the end of each file, so now `parse_xxx` can be called both as scripts and directly from pymol. Similarly, `pycg_bonds.py` can be called from pymol normally, but now can be used as a module because I moved global calls into `main()`.

I also took the chance to replace the one or two occurrences of `Path` with some `os.path` stuff, so we had more consistency among things and one less dependency :P If you prefer Path, feel free to change them back, but try to use it everywhere!

### CODE REVIEW

**Comment by brisvag** [comment]
I'm trying to use it as a module, and I'm having problems. I need to fix some stuff probably, so wait with the merge!

**Comment by brisvag** [comment]
I fixed my problems. Now it should work as expected!

**Comment by mjtadema** [comment]
> I refactore the code into a few separate moduled.
> 
>     * `pycg_bonds.py` now only contains `make_graphs` and `pycg_bonds`.
> 
>     * `parse_top` and `parse_tpr` now have each their own file
> 
>     * utility functions were all moved in `utils.py`
> 
> 
> Also, I added some shit at the end of each file, so now `parse_xxx` can be called both as scripts and directly from pymol. Similarly, `pycg_bonds.py` can be called from pymol normally, but now can be used as a module because I moved global calls into `main()`.
> 
> I also took the chance to replace the one or two occurrences of `Path` with some `os.path` stuff, so we had more consistency among things and one less dependency :P If you prefer Path, feel free to change them back, but try to use it everywhere!

I like pathlib because it's object oriented and the way forward :P besides, it's in the python standard library so there is no extra dependency.
However os.path is backwards compatible with python2.7 so for this project it might be better if we want to support it eventually.

**Comment by brisvag** [comment]
Integrated in #27.

**Pull request closed without merging**
